# https://sap.github.io/jenkins-library/
general:
  gitSshKeyCredentialsId: 'GITHUBALUNDESAP'
  collectTelemetryData: false
steps:
  setupCommonPipelineEnvironment:
    collectTelemetryData: true
  mtaBuild:
    buildTarget: 'XSA'
    defaultNpmRegistry: 'https://registry.npmjs.org/'
  dockerExecute:
    XSA:
      apiEndpoint: 'https://api.parvus.lcfx.net'
      org: 'lcfx'
      space: 'DEV'
      credentialsId: 'CF_CREDENTIALSID'
      dockerImage: 'alunde/xsa-cli'
      dockerWorkspace: '/home/jenkins/piper'
  xsDeploy:
    credentialsId: 'XS_CREDENTIALSID'
    docker:
      #dockerImage: 'alunde/xsa-cli'
      #dockerPullImage: true
      dockerImage: 'ppiper/xs-cli'
    mode: 'DEPLOY'  #[DEPLOY]/BG_DEPLOY/NONE
    action: 'NONE'  #[NONE]/RESUME/ABORT/RETRY
    apiUrl: 'https://api.parvus.lcfx.net:443/'
    space: 'DEV'
    org: 'lcfx'
    loginOpts: '--skip-ssl-validation'
    deployOpts: ''
  mailSendNotifiction:
    notificationAttachment: true
    notificationRecipients: 'andrew.lunde@sap.com'
    notifyCulprits: false
  slackSendNotification:
    credentialsId: 'SLACKSECRET'
    channel: '#jenkins_builds'